# fly.toml app configuration file generated for condemnhasan on 2026-09-04T22:47:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'condemnhasan'
primary_region = 'sjc'

[build]
  [build.args]
    GO_VERSION = '1.27.1'

[env]
  PORT = '8080'
  RESULTS_PATH = '/data/results.txt'

[[mounts]]
  source = "condemnhasan_vol"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
